name: License Scanning for Node.js

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'code/package-json.lock'
      - 'code/package.json'
      - 'code/src/ui/package.json'
      - '.github/workflows/license-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --omit=dev
        working-directory: "./code"
      - run: npm install -g node-license-validator
        working-directory: "./code"
      - run: node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD BSD-3-Clause Unlicense
        working-directory: "./code"

  scan_ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --omit=dev
        working-directory: "./code/src/ui"
      - run: npm install -g node-license-validator
        working-directory: "./code/src/ui"
      - run: node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD BSD-3-Clause Unlicense
        working-directory: "./code/src/ui"
